### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ShinNouzen** [TheRealKizu/trace.moe.ts#13]
Can you please make a method for post?

**Comment by TheRealKizu** [comment]
Elaborate please

**Comment by ShinNouzen** [comment]
> Elaborate please

Make it readable by fs

**Comment by TheRealKizu** [comment]
Oh, okay 👍

**Comment by TheRealKizu** [comment]
Added method. Update and use `<API>.fetchAnimeFromBuffer()` :)
