### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShinNouzen** [TheRealKizu/trace.moe.ts#14]
![Screenshot_20211102-144949_Chrome](https://user-images.githubusercontent.com/85594230/139819809-bda26ae1-301e-482a-ada6-751c9d1bac97.jpg)
Ahh tbh this is the first time I'm encountering this  error in npm.

**Comment by TheRealKizu** [comment]
The project is really isn't that strict typed. You can try enabling `skipLibCheck` or setting `noImplicitAny` to false on your tsconfig.json

**Comment by ShinNouzen** [comment]
it didn't work for me.

**Comment by TheRealKizu** [comment]
I think it should now
